services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: always
    ports:
      - "8000:8080"
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - BASE_URL=http://localhost:8000
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
      - ./data:/var/lib/searxng/data

networks:
  default:
    name: searx_network
    external: true